---
name: annotate
on:
  pull_request:
    branches: [ "main" ]

jobs:
  annotate:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
      - name: Run annotate and exit(1) if something is unannotated
        run: bundle exec annotate --frozen
