---
name: rubocop
on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-source-code-with-rubocop:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
